services:
  buildcollator:
    build:
      context: .
      dockerfile: Dockerfile.buildcollator
    volumes:
      - ./artefacts:/root/src/liquid-staking/artefacts
  zombienet:
    build:
      context: .
      dockerfile: Dockerfile.zombienet
    volumes:
      - ./artefacts:/home/okalice/src/liquid-staking/artefacts
    ports:
      - "9944:9944"
    depends_on:
      - buildcollator
  deploy:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    volumes:
      - ./artefacts:/root/src/liquid-staking/artefacts
    depends_on:
      - zombienet
  offchain:
    build:
      context: .
      dockerfile: Dockerfile.offchain
    volumes:
      - ./artefacts:/home/okalice/src/liquid-staking/artefacts
    depends_on:
      - deploy
