services:
  zombienet:
    build:
      context: .
      dockerfile: Dockerfile.zombienet
    ports:
      - "9944:9944"
  deploy:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    volumes:
      - ./artefacts:/root/src/liquid-staking/artefacts
    depends_on:
      - zombienet
  offchain:
    build:
      context: .
      dockerfile: Dockerfile.offchain
    volumes:
      - ./artefacts:/home/okalice/src/liquid-staking/artefacts
    depends_on:
      - deploy
