FROM docker.io/paritytech/contracts-ci-linux:latest

# metadata
LABEL dev.okalice.image.authors="wouter@okalice.dev" \
    dev.okalice.image.vendor="okAlice" \
    dev.okalice.image.description="Milestone 1 - Deploy"

COPY scripts/functions.sh /tmp
COPY scripts/fetch-contracts.sh /tmp
COPY scripts/build-and-deploy-contracts.sh /bin

RUN /tmp/fetch-contracts.sh
ENTRYPOINT [ "build-and-deploy-contracts.sh" ]


