FROM rust

# metadata
LABEL dev.okalice.image.authors="Zabuxx" \
    dev.okalice.image.vendor="okAlice" \
    dev.okalice.image.description="Milestone 1 - Build Collator"

COPY scripts/functions.sh /tmp
COPY scripts/fetch-contracts.sh /tmp
COPY scripts/build-and-deploy-collator.sh /bin

RUN apt-get -qq update && apt-get -qq install -y protobuf-compiler librocksdb-dev clang

RUN /tmp/fetch-contracts.sh
ENTRYPOINT [ "build-and-deploy-collator.sh" ]
